### ISSUE TITLE
DTSTART and RFC compatibility

### ISSUE THREAD

**Issue by rickywiens** [teambition/rrule-go#14]
Hello there,

I am working with this library for a project and I was wondering about the different ways this package handles RRULE strings compared to the python dateutil package. For example:

This string `"FREQ=DAILY;INTERVAL=10;COUNT=5;DTSTART=19980902T090000"`
While valid in rrule-go:
```go
	r, err := rrule.StrToRRule("FREQ=DAILY;INTERVAL=10;COUNT=5;DTSTART=19980902T090000")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(r)
	for _, e := range r.All() {
		fmt.Println(e)
	}
```
```
FREQ=DAILY;DTSTART=19980902T090000Z;INTERVAL=10;COUNT=5
1998-09-02 09:00:00 +0000 UTC
1998-09-12 09:00:00 +0000 UTC
1998-09-22 09:00:00 +0000 UTC
1998-10-02 09:00:00 +0000 UTC
1998-10-12 09:00:00 +0000 UTC
```

Is actually invalid according to the python dateutil library (And also RFC5545)
```
>>> rrulestr("FREQ=DAILY;INTERVAL=10;COUNT=5;DTSTART=19980902T090000")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py", line 1093, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py", line 1013, in _parse_rfc
    tzinfos=tzinfos)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py", line 975, in _parse_rfc_rrule
    raise ValueError, "unknown parameter '%s'" % name
ValueError: unknown parameter 'DTSTART'"
```

The RFC spec defines DTSTART as existing at the same level as the RRULE string like:
```
  DTSTART:19980902T090000
  RRULE:FREQ=DAILY;INTERVAL=10;COUNT=5
```

Which is not compatible with rrule-go:
```go
	rs, err := rrule.StrToRRuleSet("DTSTART:19980902T090000\n" + "RRULE:FREQ=DAILY;INTERVAL=10;COUNT=5")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(rs)
	for _, e := range rs.All() {
		fmt.Println(e)
	}
```
```
2018/08/21 13:54:44 unsupported property: DTSTART

Process finished with exit code 1
```

But is compatible with the python dateutil library:
```
>>> r = rrulestr("""
...   DTSTART:19980902T090000
...   RRULE:FREQ=DAILY;INTERVAL=10;COUNT=5
...   """)
>>> list(r)
[datetime.datetime(1998, 9, 2, 9, 0), datetime.datetime(1998, 9, 12, 9, 0), datetime.datetime(1998, 9, 22, 9, 0), datetime.datetime(1998, 10, 2, 9, 0), datetime.datetime(1998, 10, 12, 9, 0)]
>>>
```

I was wondering if the functionality of this package, which seems to be more similar to [rrule.js](https://github.com/jakubroztocil/rrule) is intentional? I am willing to contribute to this package to make it more similar to the python library and the spec, but I was wondering if that was desirable to the maintainers.

Let me know if I'm way off base here, and thanks for your time.

**Comment by zensh** [comment]
@rickywiens We are using rrule-go and rrule.js (Node.js API and web app)

**Comment by rickywiens** [comment]
It looks like rrule.js is also moving towards RFC compliance:

https://github.com/jakubroztocil/rrule/issues/83

https://github.com/jakubroztocil/rrule/pull/269

Would you be open to a PR that brings this library in line with the RFC and rrule.js without breaking changes?

**Comment by rickywiens** [comment]
Please see #15

**Comment by zensh** [comment]
@rickywiens Thank you, I will review it in next day

**Comment by zensh** [comment]
@rickywiens Thank you, v1.2.0 released.
