### ISSUE TITLE
Library utilization

### ISSUE THREAD

**Issue by luxifer** [teambition/rrule-go#17]
Hi, do you mind if I use your library for my iCal parser ? https://github.com/luxifer/ical

**Comment by rickywiens** [comment]
You might find some of this discussion interesting:

https://github.com/teambition/rrule-go/pull/15

This package practically speaking is more concerned with parsing RRULES like other libraries do than specifically adhering to the RFC standard. If you are interested in a true RFC parser, this may not be the best way to go about it.
