### ISSUE TITLE
Add a go.mod file

### ISSUE THREAD

**Issue by srikrsna** [teambition/rrule-go#21]
It will be nice to have a go.mod file.

**Comment by srikrsna** [comment]
Any thoughts on this?

**Comment by zensh** [comment]
go.mod is every nice, but there is no external dependence

**Comment by srikrsna** [comment]
go.mod is not just for external dependencies. It can at least be used to work outside `GOPATH` and a good way to future proof where go.mod will be requirement.

**Comment by zensh** [comment]
@srikrsna That is good

**Comment by srikrsna** [comment]
Shall I send a PR?

**Comment by zensh** [comment]
@srikrsna It is welcome
