### ISSUE TITLE
StrToRule doesn't follow RFC5545

### ISSUE THREAD

**Issue by ncapdevi** [teambition/rrule-go#36]
According to  https://tools.ietf.org/html/rfc5545 
A rrule string such as:
`DTSTART:20120201T093000Z\nRRULE:FREQ=WEEKLY;INTERVAL=5;UNTIL=20130130T230000Z;BYDAY=MO,FR`
and is the kind of string returned from the fairly popular library https://github.com/jakubroztocil/rrule with demo here https://jakubroztocil.github.io/rrule/

However, this string won't work for two reasons,
1. The standardized "RRULE:" Prefix from the RFC doc
2. The new line `\n` format to separate the rules.

It seems like the library doesn't fully support the standard, although I may be wrong.

**Comment by dolmen** [comment]
[`StrToRRuleSet`](https://pkg.go.dev/github.com/teambition/rrule-go?tab=doc#StrToRRuleSet) exists for that purpose.

Here is an example on the Go Playground: https://play.golang.org/p/ZSmwJNUVnWh
